# Generated by Django 6.0.1 on 2026-01-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_is_featured_order_orderitem_productimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Método de Pagamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Método de Envio')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Minha Loja', max_length=100, verbose_name='Nome da Loja')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='Imagem do Banner')),
                ('banner_title', models.CharField(blank=True, max_length=100, verbose_name='Título do Banner')),
                ('banner_text', models.TextField(blank=True, verbose_name='Texto do Banner')),
                ('primary_color', models.CharField(default='#000000', help_text='Ex: #FF0000', max_length=7, verbose_name='Cor Principal (Hex)')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de Contacto')),
            ],
            options={
                'verbose_name': 'Configuração da Loja',
                'verbose_name_plural': 'Configurações da Loja',
            },
        ),
    ]
