# Generated by Django 6.0.1 on 2026-01-29 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_administrator_client_order_payment_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ceremony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome da Cerimónia')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('image', models.ImageField(upload_to='ceremonies/', verbose_name='Imagem')),
                ('event_date', models.DateTimeField(verbose_name='Data de Realização')),
            ],
        ),
        migrations.CreateModel(
            name='CeremonyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('payment_preference', models.CharField(help_text='Ex: Transferência, MBWAY, Numerário', max_length=100, verbose_name='Preferência de Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ceremony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='store.ceremony')),
            ],
        ),
    ]
