# Generated by Django 6.0.1 on 2026-01-30 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_sitesettings_address_sitesettings_facebook_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceremonyregistration',
            name='payment_preference',
        ),
        migrations.AddField(
            model_name='ceremonyregistration',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.paymentmethod', verbose_name='Método de Pagamento'),
        ),
        migrations.AddField(
            model_name='ceremonyregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ceremony_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Anamnesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('health_issues', models.TextField(blank=True, help_text='Tem algum problema de saúde que devamos saber?', verbose_name='Problemas de Saúde')),
                ('medications', models.TextField(blank=True, help_text='Toma alguma medicação regular?', verbose_name='Medicação')),
                ('surgeries', models.TextField(blank=True, verbose_name='Cirurgias Recentes')),
                ('goals', models.TextField(blank=True, help_text='Qual a sua intenção com esta cerimónia?', verbose_name='Objetivos / Intenções')),
                ('observations', models.TextField(blank=True, verbose_name='Outras Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis', to='store.ceremonyregistration', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Ficha de Anamnese',
                'verbose_name_plural': 'Fichas de Anamnese',
            },
        ),
    ]
