# Generated by Django 6.0.1 on 2026-01-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_ceremonyregistration_payment_preference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceremony',
            name='max_participants',
            field=models.PositiveIntegerField(default=0, help_text='0 para ilimitado', verbose_name='Máximo de Participantes'),
        ),
        migrations.AddField(
            model_name='ceremony',
            name='requirements',
            field=models.TextField(blank=True, help_text='Informação visível apenas após a inscrição (ex: jejum, o que levar, etc)', verbose_name='Requisitos e Conselhos'),
        ),
    ]
