# Generated by Django 6.0.1 on 2026-01-30 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_therapy_appointment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Marcação', 'verbose_name_plural': 'Marcações'},
        ),
        migrations.AlterModelOptions(
            name='ceremony',
            options={'verbose_name': 'Cerimónia', 'verbose_name_plural': 'Cerimónias'},
        ),
        migrations.AlterModelOptions(
            name='ceremonyregistration',
            options={'verbose_name': 'Inscrição em Cerimónia', 'verbose_name_plural': 'Inscrições em Cerimónias'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Método de Pagamento', 'verbose_name_plural': 'Métodos de Pagamento'},
        ),
        migrations.AlterModelOptions(
            name='shippingmethod',
            options={'verbose_name': 'Método de Envio', 'verbose_name_plural': 'Métodos de Envio'},
        ),
        migrations.AlterModelOptions(
            name='therapy',
            options={'verbose_name': 'Terapia', 'verbose_name_plural': 'Terapias'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.paymentmethod', verbose_name='Método de Pagamento'),
        ),
    ]
